FROM python:3.11.7-slim-bookworm

COPY py-requirements.txt ./

# required to build the ndd python package
# RUN sudo apt install gfortran

# RUN pip install -r py-requirements.txt

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y gfortran && rm -rf /var/lib/apt/lists/*

# required before ndd can be installed
RUN pip install numpy
RUN pip install -r py-requirements.txt